apiVersion: apps/v1
kind: Deployment
metadata:
  name: website-deployment
  labels:
    env: local
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-container
  template:
    metadata:
      labels:
        app: website-container
    spec:
      containers:
        - name: website
          image: website:1.0.1
          ports:
            - containerPort: 8000
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: user

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: password

            - name: POSTGRES_HOST
              value: postgres-service